### ISSUE TITLE
IDL-to-C++11 v1.4

### ISSUE THREAD

**Issue by mitza-oci** [RemedyIT/taox11#10]
- [x] CPP1114-3 Make mapping of sequences more flexible (may not need any change)
- [ ] CPP1114-6 Fixed
- [x] CPP1114-14 Unions
- [x] CPP1114-31 Delegation-based interface implementation (may not need any change)

https://issues.omg.org/issues/spec/CPP11/1.4/fixed

**Comment by jwillemsen** [comment]
Currently TAOX11 is aiming for IDL to C++11 v1.3 compliance. For the delegation support we have internal tracking id 3736 and for unions 4719

**Comment by jwillemsen** [comment]
For support for CPP1114-31 see https://github.com/RemedyIT/taox11/pull/22

**Comment by jwillemsen** [comment]
For support CP1114-14 see https://github.com/RemedyIT/taox11/pull/243

**Comment by jwillemsen** [comment]
TAOX11 lacks full support for Fixed but looking at the latest revision the proposed mapping will probably not work for the type traits as there is no distinct type, just one class in the proposed mapping.

**Comment by jwillemsen** [comment]
Closing, the proposed spec changes for Fixed will not work as far as I can analyze right now. Fixed is just a noop in TAO/TAOX11
