### ISSUE TITLE
-in    Option  to generate <>s for standard #include'd files does not work

### ISSUE THREAD

**Issue by ClausKlein** [RemedyIT/taox11#215]
**Version**
RIDL compiler 2.8.1

**Describe the bug**
the option -in does not change the generated code!

**Comment by jwillemsen** [comment]
Transferred this issue to the taox11 repository, ridl is only the front end, it doesn't do any code generation. The `-in` option is part of taox11 (see https://github.com/RemedyIT/taox11/blob/b3a2910adb597a76c79ccf42c0be43509f540d06/ridlbe/c%2B%2B11/config.rb#L23)

**Comment by mcorino** [comment]
This switch is/was intended to provide command-line option compatibility with TAOIDL.

**Comment by ClausKlein** [comment]
The implementation of this option would be very helpful to prevent warnings from system headers (i.e. ace, or taox11 headers)

see https://github.com/friendlyanon/cmake-init-shared-static/blob/master/cmake/variables.cmake#L24

and https://github.com/aminya/project_options#target_include_system_directories-function

**Comment by mcorino** [comment]
According to what specification/definition should ACE, TAO or TAOX11 headers be considered "system" headers?

**Comment by ClausKlein** [comment]
According my `CMakeLists.txt` project configuration files.
We use `CMake` to generate our build files, I have control of all I want to do.
But the `ridlc` should respect the options I use!

**Comment by mcorino** [comment]
> According my `CMakeLists.txt` project configuration files. We use `CMake` to generate our build files, I have control of all I want to do. But the `ridlc` should respect the options I use!

I don't see why. CMake is just one of many available build tools. I do not see why such a tool (for which TAOX11 has no support yet) should prescribe the behavior of an IDL compiler.
We might accept logical arguments why generating '<>' includes in certain circumstances could be preferred over '""' includes but this is not one of those.
In any case it might be wise to arrange budget to have any such changes made. TAOX11 is a fully open source project *but* our support for adding new features and enhancements or helping users build applications with TAOX11 is 100% commercial.

**Comment by ClausKlein** [comment]
yes, I know.
But this is a BUG, fix it!

**Comment by jwillemsen** [comment]
Also bug fixing is a commercial service, see https://www.remedy.nl/services/opensource-support.html for our services.

**Comment by mcorino** [comment]
> yes, I know. But this is a BUG, fix it!

I do not see how this is a bug. 
It's an intended feature of TAOX11 RIDLC and causes no errors, build or runtime problems in the regular, standard and supported builds of TAOX11.
You seem to have another build setup that somehow triggers (relatively innocent) compile (?) warnings and you would like to have a solution to have those removed. That sounds to me more like a feature request.

Also, it might be best to remember that simple politeness often works better when discussing feature requests.
Shouting (using capitals) does nothing to promote your case and posing demands like "fix it!" is absolutely not done.
Open source licenses provide freedom of use but nothing more. Nobody is in anyway obligated to help fix your problems and definitely not obligated to respond to "demands".

**Comment by ClausKlein** [comment]
I will help me myself, your support is a farce!
